import { addIcons } from 'ionicons';
import {
    chatboxOutline,
    chevronBack,
    chevronForward,
    pencil,
    peopleCircle,
    personOutline,
    qrCode,
    radioButtonOff,
    radioButtonOn,
    notificationsOutline, chevronForwardOutline, addOutline,
    arrowForwardOutline, shareSocialOutline, checkmarkCircle,
    addCircleOutline, diamondOutline,
    peopleCircleOutline,
    ellipsisVerticalOutline,
    checkmarkDoneOutline,
    trashOutline,
    cashOutline,
    peopleOutline,
    megaphoneOutline,
    timeOutline,
    checkmarkCircleOutline,
    alertCircleOutline,
    helpCircleOutline,
    searchOutline,
    walletOutline,
    calendarOutline,
    chevronBackOutline, closeOutline,
    imageOutline, pencilOutline,
    shareOutline, qrCodeOutline, copyOutline, downloadOutline, refreshOutline, shieldCheckmarkOutline,
    listOutline, shuffleOutline,
    logoWhatsapp,
    logoTwitter,
    logoSnapchat,
    syncOutline,
    repeatOutline,
    flagOutline,
    personAddOutline,
    lockClosedOutline,
    playCircleOutline,
    homeOutline,
    closeCircleOutline,
    informationCircleOutline,
    thumbsUpOutline,
    handLeftOutline,
    cameraOutline,
    cardOutline,
    sendOutline,
    headsetOutline,
    logOutOutline,
    callOutline,
    rocketOutline,
    openOutline,
    starOutline,
    flashOutline,
    infiniteOutline,
    trendingUpOutline,
    sparkles,
    closeCircle,
    linkOutline,
    informationCircle,
    rocket,
    chatbubbleOutline,
    statsChartOutline,
    ellipseOutline,
    receiptOutline,
    card,
    paperPlane,
    paperPlaneOutline,
    trophyOutline,
    chevronDownOutline,
    chevronUpOutline,
    settingsOutline,
    personRemoveOutline,
    shieldOutline,
    swapHorizontalOutline,
    thumbsDownOutline,
    diamond,
    checkmarkOutline,
    enterOutline,
    arrowForwardCircleOutline,
} from 'ionicons/icons';

export function registerIcons() {
    addIcons({
        chevronBack,
        chevronForward,
        peopleCircle,
        qrCode,
        radioButtonOn,
        radioButtonOff,
        personOutline,
        pencil,
        chatboxOutline,
        notificationsOutline, chevronForwardOutline, addOutline,
        arrowForwardOutline, shareSocialOutline, checkmarkCircle,
        addCircleOutline, diamondOutline, peopleCircleOutline,
        checkmarkDoneOutline, trashOutline,
        ellipsisVerticalOutline, cashOutline, peopleOutline,
        alertCircleOutline, checkmarkCircleOutline, megaphoneOutline, timeOutline,
        helpCircleOutline, arrowForwardCircleOutline,
        searchOutline,
        walletOutline, chevronUpOutline,
        calendarOutline, trophyOutline, chevronDownOutline,
        chevronBackOutline, closeOutline,
        imageOutline, pencilOutline,
        shareOutline, qrCodeOutline, copyOutline, downloadOutline,
        refreshOutline, paperPlaneOutline,
        shieldCheckmarkOutline, checkmarkOutline, enterOutline,
        listOutline, shuffleOutline, logoWhatsapp, logoTwitter, logoSnapchat, syncOutline,
        repeatOutline, flagOutline, playCircleOutline, personAddOutline, lockClosedOutline,
        homeOutline, closeCircleOutline, informationCircleOutline, thumbsUpOutline,
        handLeftOutline, cameraOutline, diamond,
        cardOutline, receiptOutline,
        sendOutline, headsetOutline, logOutOutline,
        callOutline, ellipseOutline, settingsOutline,
        rocketOutline, openOutline, card, thumbsDownOutline,
        infiniteOutline, rocket, statsChartOutline,
        trendingUpOutline, starOutline, flashOutline,
        sparkles, closeCircle, linkOutline, informationCircle, chatbubbleOutline,
        personRemoveOutline, shieldOutline, swapHorizontalOutline
    });
}